apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: catalog-service
build:
  artifacts:
    - image: catalog-service
      jib: {}
  local:
    push: false

deploy:
  kubectl:
    manifests:
      - k8s/base/deployment.yaml
      - k8s/base/service.yaml
