apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: catalog-service
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: catalog-service
      jib: {}

profiles:
  - name: monkey
    activation:
      - kubeContext: dev/console-c3smonkey-ch:8443/developer
    build:
      insecureRegistries:
        - registry.apps.c3smonkey.ch
      tagPolicy:
        sha256: {}
      artifacts:
        - image: registry.apps.c3smonkey.ch/dev/catalog-service
          jib:
            args: ['-Dimage=registry.apps.c3smonkey.ch/dev/catalog-service']
    deploy:
      kustomize:
        paths: ["k8s/overlays/dev"]

  - name: local
    build:
      tagPolicy:
        sha256: {}
      artifacts:
        - image: customer-service
          jib: {}
      local:
        push: false

