management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    restart:
      enabled: true

opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: http://localhost:14268/api/traces

ribbon:
  http:
    client:
      enabled: true


app:
  name: MyApp
  description: ${app.name} is a Spring Boot application ${random.uuid}


---
server:
  port: 8081
spring:
  profiles: local
