apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: catalog-service
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: MEM_TOTAL_MB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory

